'use strict';

// Define navigator.mediaDevices.getUserMedia() for older devices.

/**
 * Constraints to apply to MediaStream.
 * On this codelab, we will be streaming video, but not audio.
 * @type {!MediaStreamConstraints}
 */
const mediaStreamConstraints = {
  audio: false,
  video: true,
};

/** @type {!Element} Video element where stream will be placed. */
const localVideo = document.querySelector('video');

/**
 * Handles success by adding the MediaStream to the video element.
 * @param {!MediaStream} mediaStream generated by getUserMedia to add to video.
 */
const localMediaStreamSuccessCallback = (mediaStream) => {
  window.localStream = mediaStream;  // Makes stream available to the console.
  if (window.URL) {
    localVideo.src = window.URL.createObjectURL(mediaStream);
  } else {
    localVideo.src = mediaStream;
  }
};

/**
 * Handles error by logging a message to the console with the error message.
 * @param {!Error} error that was generated by getUserMedia.
 */
const localMediaStreamErrorCallback = (error) => {
  console.log('navigator.getUserMedia error: ', error);
};

// Initializes media stream.
navigator.mediaDevices.getUserMedia(mediaStreamConstraints)
  .then(localMediaStreamSuccessCallback, localMediaStreamErrorCallback);
